org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Chaquopy no usa soporte androidx, pero el flag evita avisos de AGP 8.
android.useAndroidX=true

# Los recursos comprimidos se sirven mejor desde el APK sin recomprimir
# (mejora la extraccion de templates/static de Python).
android.enableResourceOptimizations=true
